### ISSUE TITLE
Ruby ci-queue requires gems that are not runtime dependencies

### ISSUE THREAD

**Issue by RobertMic** [Shopify/ci-queue#156]
We are getting `LoadError: cannot load such file` errors from the `ci-queue` ruby gem when trying to use it. It looks to me that the gem specifies several `development_dependencies` but uses them outside of development at runtime.

The fix on our end is to require this gems dependencies in our `gemfile`. The gem should properly specify its dependencies so installing it via `bundler` will grab everything it needs.

Here are the errors I've encountered:
```
bundler: failed to load command: minitest-queue (/tmp/bundle/ruby/2.7.0/bin/minitest-queue)
--
  | LoadError: cannot load such file -- redis
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/ci/queue/redis.rb:3:in `require'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/ci/queue/redis.rb:3:in `<top (required)>'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/ci/queue.rb:47:in `require'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/ci/queue.rb:47:in `from_uri'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/minitest/queue/runner.rb:31:in `run!'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/minitest/queue/runner.rb:19:in `invoke'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/exe/minitest-queue:5:in `<top (required)>'
  | /tmp/bundle/ruby/2.7.0/bin/minitest-queue:23:in `load'
  | /tmp/bundle/ruby/2.7.0/bin/minitest-queue:23:in `<top (required)>'
```
```
bundler: failed to load command: minitest-queue (/tmp/bundle/ruby/2.7.0/bin/minitest-queue)
--
  | LoadError: cannot load such file -- minitest/reporters
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/minitest/queue.rb:4:in `require'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/minitest/queue.rb:4:in `<top (required)>'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/minitest/queue/runner.rb:4:in `require'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/minitest/queue/runner.rb:4:in `<top (required)>'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/exe/minitest-queue:4:in `require'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/exe/minitest-queue:4:in `<top (required)>'
  | /tmp/bundle/ruby/2.7.0/bin/minitest-queue:23:in `load'
  | /tmp/bundle/ruby/2.7.0/bin/minitest-queue:23:in `<top (required)>'
```

**Comment by casperisfine** [comment]
See https://github.com/Shopify/ci-queue/pull/153 for minitest-reporters.

As for Redis it's a bit of the same. There are alternative queue implementation that don't use Redis. But I guess I would agree that 99% of users want the Redis queue so yeah we can add it to the gemspec.

**Comment by RobertMic** [comment]
Ahh I see the predicament, I guess https://github.com/Shopify/ci-queue/issues/60 is needed for something like this then? In the meantime would it be reasonable to document the additional dependencies (depending on use case) in the `README`? I know it would have saved me some time if that documentation existed 😄.

**Comment by casperisfine** [comment]
> In the meantime would it be reasonable to document the additional dependencies (depending on use case) in the `README`?

Since we deprecated rspec support, it would probably be simpler to cut a `1.0` release with only minitest support, and adding the proper dependencies.
