### ISSUE TITLE
`minitest-queue` `ENOENT` error if `log` folder does not exist

### ISSUE THREAD

**Issue by RobertMic** [Shopify/ci-queue#158]
👋  Running into a `ENOENT` error when the gem tries to open up the `log/test_order.log` file and the `log` directory does not exist.

Running this command on CI:
```
bundle exec minitest-queue run --max-requeues 3 --requeue-tolerance 0.01 --timeout 45 -Itest:lib $(find test -name \*_test.rb | sort)
```

Causes this error:
```
/usr/local/bundle/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
--
  | Traceback (most recent call last):
  | 8: from /tmp/bundle/ruby/2.7.0/gems/minitest-5.14.1/lib/minitest.rb:68:in `block in autorun'
  | 7: from /tmp/bundle/ruby/2.7.0/gems/minitest-5.14.1/lib/minitest.rb:139:in `run'
  | 6: from /tmp/bundle/ruby/2.7.0/gems/minitest-5.14.1/lib/minitest.rb:849:in `start'
  | 5: from /tmp/bundle/ruby/2.7.0/gems/minitest-5.14.1/lib/minitest.rb:849:in `each'
  | 4: from /tmp/bundle/ruby/2.7.0/gems/minitest-reporters-1.4.2/lib/minitest/minitest_reporter_plugin.rb:16:in `start'
  | 3: from /tmp/bundle/ruby/2.7.0/gems/minitest-reporters-1.4.2/lib/minitest/minitest_reporter_plugin.rb:16:in `each'
  | 2: from /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/minitest/queue/order_reporter.rb:11:in `start'
  | 1: from /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/minitest/queue/order_reporter.rb:11:in `open'
  | /tmp/bundle/ruby/2.7.0/gems/ci-queue-0.20.5/lib/minitest/queue/order_reporter.rb:11:in `initialize': No such file or directory @ rb_sysopen - log/test_order.log (Errno::ENOENT)
```

Committing an empty `log` folder at the root of my repo fixes it. The folder should just be created on its own if it doesn't exist and is required at runtime.

**Comment by casperisfine** [comment]
Yeah, PR welcome.
