### ISSUE TITLE
Error thrown when no worker-id is present when redis > 5.0.0

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [Shopify/ci-queue#192]
Since we updated [redis](https://github.com/redis/redis-rb) to 5.0.5, we are facing errors whenever worker-id is not present:

```
$ bundle exec minitest-queue run -Itest $(find test -name \*_test.rb | sort)

bundler: failed to load command: minitest-queue (/tmp/bundle/ruby/3.1.0/bin/minitest-queue)
W, [2022-10-04T21:09:42.446048 #241]  WARN -- : calling Tracer#shutdown multiple times.
/tmp/bundle/ruby/3.1.0/gems/redis-client-0.9.0/lib/redis_client/command_builder.rb:37:in `block in generate': Unsupported command argument type: NilClass (TypeError)
	from /tmp/bundle/ruby/3.1.0/gems/redis-client-0.9.0/lib/redis_client/command_builder.rb:28:in `map!'
	from /tmp/bundle/ruby/3.1.0/gems/redis-client-0.9.0/lib/redis_client/command_builder.rb:28:in `generate'
	from /tmp/bundle/ruby/3.1.0/gems/redis-client-0.9.0/lib/redis_client.rb:211:in `call_v'
	from /tmp/bundle/ruby/3.1.0/gems/redis-5.0.5/lib/redis/client.rb:73:in `call_v'
	from /tmp/bundle/ruby/3.1.0/gems/redis-5.0.5/lib/redis.rb:167:in `block in send_command'
	from /tmp/bundle/ruby/3.1.0/gems/redis-5.0.5/lib/redis.rb:166:in `synchronize'
	from /tmp/bundle/ruby/3.1.0/gems/redis-5.0.5/lib/redis.rb:166:in `send_command'
	from /tmp/bundle/ruby/3.1.0/gems/redis-5.0.5/lib/redis/commands/sets.rb:21:in `sadd'
	from /tmp/bundle/ruby/3.1.0/gems/ci-queue-0.24.2/lib/ci/queue/redis/worker.rb:218:in `register'
	from /tmp/bundle/ruby/3.1.0/gems/ci-queue-0.24.2/lib/ci/queue/redis/worker.rb:211:in `push'
	from /tmp/bundle/ruby/3.1.0/gems/ci-queue-0.24.2/lib/ci/queue/redis/worker.rb:27:in `populate'
	from /tmp/bundle/ruby/3.1.0/gems/ci-queue-0.24.2/lib/minitest/queue/runner.rb:282:in `populate_queue'
	from /tmp/bundle/ruby/3.1.0/gems/ci-queue-0.24.2/lib/minitest/queue/runner.rb:87:in `run_command'
	from /tmp/bundle/ruby/3.1.0/gems/ci-queue-0.24.2/lib/minitest/queue/runner.rb:38:in `public_send'
	from /tmp/bundle/ruby/3.1.0/gems/ci-queue-0.24.2/lib/minitest/queue/runner.rb:38:in `run!'
	from /tmp/bundle/ruby/3.1.0/gems/ci-queue-0.24.2/lib/minitest/queue/runner.rb:19:in `invoke'
	from /tmp/bundle/ruby/3.1.0/gems/ci-queue-0.24.2/exe/minitest-queue:5:in `<top (required)>'
	from /tmp/bundle/ruby/3.1.0/bin/minitest-queue:25:in `load'
	from /tmp/bundle/ruby/3.1.0/bin/minitest-queue:25:in `<top (required)>'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in `exec'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
	from /usr/local/ruby/bin/bundle:25:in `load'
	from /usr/local/ruby/bin/bundle:25:in `<main>'
```

This problem only appears when `worker_id` is nil, since we send it down to redis which is now doing more strict type checking.

I think in the ideal scenario, worker_id should never be nil, but in that case, the command should fail in argument validation whenever no worker ID was provided or inferred, instead of failing when trying to access redis

**Comment by casperisfine** [comment]
Interesting. In `4.x` `redis-rb` would cast `nil` as `""` which suggest this bug was always there, just silently making something it shouldn't.

We should exit early if we have no `build_id`.

**Comment by casperisfine** [comment]
Nah, it's explicitly showing a pre-exiting nasty bug. No need for a major. Also we don't claim semver.

**Comment by AbdulRahmanAlHamali** [comment]
I can submit a PR to do the validations. Is there anything other than `worker_id` that must not be nil?

**Comment by casperisfine** [comment]
> Is there anything other than `worker_id` that must not be nil?

Sorry, somehow missed that message. Nothing should ever be nil.

**Comment by casperisfine** [comment]
This was fixed in https://github.com/Shopify/ci-queue/pull/198
